name: Update GitHub Trending

on:
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2:00 UTC (adjustable)
  workflow_dispatch:

jobs:
  update-trending:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch GitHub Trending
        run: python main.py fetch

      - name: Analyze and Generate Webpage
        run: python main.py analyze

      - name: Send Subscription Emails
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        run: python src/subscription/manager.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/trending_data/ docs/index.html data/subscriptions.json
          git commit -m 'chore: update trending data and webpage [auto]' || echo 'No changes to commit'
          git push